[package]
name = "fluorite-cast"
license = "MIT"
version = "0.1.1"
edition = "2024"
authors = ["StarlightSora"]
description = "Ballistics Engine / Projectile Casting Simulation for Godot 4"
repository = "https://github.com/StarlightSora/fluorite-cast"
keywords = ["gamedev", "godot", "projectile", "raycast"]
categories = ["game-development", "mathematics"]
exclude = [
    "examples/scenes",
]
#publish = false # Suppress publishing during dev build

[features]

[dependencies]
godot = { version = "0.5", features = ["upcoming-editor-placeholders"] }
hashbrown = { version = "0.17" }

[profile.dev]
opt-level = 1

## Uncomment below two lines if building a standalone cdylib build
#[lib]
#crate-type = ["cdylib"]